package server

import "github.com/labstack/echo"

func RegisterController(name string, e *echo.Echo, m []echo.Middleware, config Config) {
	rc := ResourceController{name}
	rcBase := e.Group("/" + name)
	rcBase.Get("", rc.IndexHandler)
	rcBase.Post("", rc.CreateHandler)

	rcItem := rcBase.Group("/:id")
	rcItem.Get("", rc.ShowHandler)
	rcItem.Put("", rc.UpdateHandler)
	rcItem.Delete("", rc.DeleteHandler)

	if len(m) > 0 {
		rcBase.Use(m...)
	}

	if config.UseSmartAuth {
		rcBase.Use(SmartAuthHandler(name))
	}
}

func RegisterRoutes(e *echo.Echo, config map[string][]echo.Middleware, serverConfig Config) {

	// Batch Support

	e.Post("/", BatchHandler)

	// Resources

	RegisterController("Appointment", e, config["Appointment"], serverConfig)
	RegisterController("ReferralRequest", e, config["ReferralRequest"], serverConfig)
	RegisterController("Account", e, config["Account"], serverConfig)
	RegisterController("Provenance", e, config["Provenance"], serverConfig)
	RegisterController("Questionnaire", e, config["Questionnaire"], serverConfig)
	RegisterController("ExplanationOfBenefit", e, config["ExplanationOfBenefit"], serverConfig)
	RegisterController("DocumentManifest", e, config["DocumentManifest"], serverConfig)
	RegisterController("Specimen", e, config["Specimen"], serverConfig)
	RegisterController("AllergyIntolerance", e, config["AllergyIntolerance"], serverConfig)
	RegisterController("CarePlan", e, config["CarePlan"], serverConfig)
	RegisterController("Goal", e, config["Goal"], serverConfig)
	RegisterController("StructureDefinition", e, config["StructureDefinition"], serverConfig)
	RegisterController("EnrollmentRequest", e, config["EnrollmentRequest"], serverConfig)
	RegisterController("EpisodeOfCare", e, config["EpisodeOfCare"], serverConfig)
	RegisterController("OperationOutcome", e, config["OperationOutcome"], serverConfig)
	RegisterController("Medication", e, config["Medication"], serverConfig)
	RegisterController("Procedure", e, config["Procedure"], serverConfig)
	RegisterController("List", e, config["List"], serverConfig)
	RegisterController("ConceptMap", e, config["ConceptMap"], serverConfig)
	RegisterController("Subscription", e, config["Subscription"], serverConfig)
	RegisterController("ValueSet", e, config["ValueSet"], serverConfig)
	RegisterController("OperationDefinition", e, config["OperationDefinition"], serverConfig)
	RegisterController("DocumentReference", e, config["DocumentReference"], serverConfig)
	RegisterController("Order", e, config["Order"], serverConfig)
	RegisterController("Immunization", e, config["Immunization"], serverConfig)
	RegisterController("Device", e, config["Device"], serverConfig)
	RegisterController("VisionPrescription", e, config["VisionPrescription"], serverConfig)
	RegisterController("Media", e, config["Media"], serverConfig)
	RegisterController("Conformance", e, config["Conformance"], serverConfig)
	RegisterController("ProcedureRequest", e, config["ProcedureRequest"], serverConfig)
	RegisterController("EligibilityResponse", e, config["EligibilityResponse"], serverConfig)
	RegisterController("DeviceUseRequest", e, config["DeviceUseRequest"], serverConfig)
	RegisterController("DeviceMetric", e, config["DeviceMetric"], serverConfig)
	RegisterController("Flag", e, config["Flag"], serverConfig)
	RegisterController("RelatedPerson", e, config["RelatedPerson"], serverConfig)
	RegisterController("SupplyRequest", e, config["SupplyRequest"], serverConfig)
	RegisterController("Practitioner", e, config["Practitioner"], serverConfig)
	RegisterController("AppointmentResponse", e, config["AppointmentResponse"], serverConfig)
	RegisterController("Observation", e, config["Observation"], serverConfig)
	RegisterController("MedicationAdministration", e, config["MedicationAdministration"], serverConfig)
	RegisterController("Slot", e, config["Slot"], serverConfig)
	RegisterController("EnrollmentResponse", e, config["EnrollmentResponse"], serverConfig)
	RegisterController("Binary", e, config["Binary"], serverConfig)
	RegisterController("MedicationStatement", e, config["MedicationStatement"], serverConfig)
	RegisterController("Person", e, config["Person"], serverConfig)
	RegisterController("Contract", e, config["Contract"], serverConfig)
	RegisterController("CommunicationRequest", e, config["CommunicationRequest"], serverConfig)
	RegisterController("RiskAssessment", e, config["RiskAssessment"], serverConfig)
	RegisterController("TestScript", e, config["TestScript"], serverConfig)
	RegisterController("Basic", e, config["Basic"], serverConfig)
	RegisterController("Group", e, config["Group"], serverConfig)
	RegisterController("PaymentNotice", e, config["PaymentNotice"], serverConfig)
	RegisterController("Organization", e, config["Organization"], serverConfig)
	RegisterController("ImplementationGuide", e, config["ImplementationGuide"], serverConfig)
	RegisterController("ClaimResponse", e, config["ClaimResponse"], serverConfig)
	RegisterController("EligibilityRequest", e, config["EligibilityRequest"], serverConfig)
	RegisterController("ProcessRequest", e, config["ProcessRequest"], serverConfig)
	RegisterController("MedicationDispense", e, config["MedicationDispense"], serverConfig)
	RegisterController("DiagnosticReport", e, config["DiagnosticReport"], serverConfig)
	RegisterController("ImagingStudy", e, config["ImagingStudy"], serverConfig)
	RegisterController("ImagingObjectSelection", e, config["ImagingObjectSelection"], serverConfig)
	RegisterController("HealthcareService", e, config["HealthcareService"], serverConfig)
	RegisterController("DataElement", e, config["DataElement"], serverConfig)
	RegisterController("DeviceComponent", e, config["DeviceComponent"], serverConfig)
	RegisterController("FamilyMemberHistory", e, config["FamilyMemberHistory"], serverConfig)
	RegisterController("NutritionOrder", e, config["NutritionOrder"], serverConfig)
	RegisterController("Encounter", e, config["Encounter"], serverConfig)
	RegisterController("Substance", e, config["Substance"], serverConfig)
	RegisterController("AuditEvent", e, config["AuditEvent"], serverConfig)
	RegisterController("MedicationOrder", e, config["MedicationOrder"], serverConfig)
	RegisterController("SearchParameter", e, config["SearchParameter"], serverConfig)
	RegisterController("PaymentReconciliation", e, config["PaymentReconciliation"], serverConfig)
	RegisterController("Communication", e, config["Communication"], serverConfig)
	RegisterController("Condition", e, config["Condition"], serverConfig)
	RegisterController("Composition", e, config["Composition"], serverConfig)
	RegisterController("DetectedIssue", e, config["DetectedIssue"], serverConfig)
	RegisterController("Bundle", e, config["Bundle"], serverConfig)
	RegisterController("DiagnosticOrder", e, config["DiagnosticOrder"], serverConfig)
	RegisterController("Patient", e, config["Patient"], serverConfig)
	RegisterController("OrderResponse", e, config["OrderResponse"], serverConfig)
	RegisterController("Coverage", e, config["Coverage"], serverConfig)
	RegisterController("QuestionnaireResponse", e, config["QuestionnaireResponse"], serverConfig)
	RegisterController("DeviceUseStatement", e, config["DeviceUseStatement"], serverConfig)
	RegisterController("ProcessResponse", e, config["ProcessResponse"], serverConfig)
	RegisterController("NamingSystem", e, config["NamingSystem"], serverConfig)
	RegisterController("Schedule", e, config["Schedule"], serverConfig)
	RegisterController("SupplyDelivery", e, config["SupplyDelivery"], serverConfig)
	RegisterController("ClinicalImpression", e, config["ClinicalImpression"], serverConfig)
	RegisterController("MessageHeader", e, config["MessageHeader"], serverConfig)
	RegisterController("Claim", e, config["Claim"], serverConfig)
	RegisterController("ImmunizationRecommendation", e, config["ImmunizationRecommendation"], serverConfig)
	RegisterController("Location", e, config["Location"], serverConfig)
	RegisterController("BodySite", e, config["BodySite"], serverConfig)
}
